// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package biblAudio;

public interface ServeurIcePrx extends Ice.ObjectPrx
{
    public void afficherMorceaux();

    public void afficherMorceaux(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_afficherMorceaux();

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_afficherMorceaux(Ice.Callback __cb);

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_afficherMorceaux(Callback_ServeurIce_afficherMorceaux __cb);

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, Callback_ServeurIce_afficherMorceaux __cb);

    public Ice.AsyncResult begin_afficherMorceaux(IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_afficherMorceaux(IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_afficherMorceaux(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public void end_afficherMorceaux(Ice.AsyncResult __result);

    public Morceau bRechercherMorceau(String sNomMusique);

    public Morceau bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, Ice.Callback __cb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, Callback_ServeurIce_bRechercherMorceau __cb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, java.util.Map<String, String> __ctx, Callback_ServeurIce_bRechercherMorceau __cb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bRechercherMorceau(String sNomMusique, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<Morceau> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public Morceau end_bRechercherMorceau(Ice.AsyncResult __result);

    public boolean bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie);

    public boolean bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, Ice.Callback __cb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, Callback_ServeurIce_bAjoutMorceau __cb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, String sNomMorc, String sFic, int uiDureeMorc, int uiDateSortie, java.util.Map<String, String> __ctx, Callback_ServeurIce_bAjoutMorceau __cb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bAjoutMorceau(String sNomArt, 
                                               String sNomMorc, 
                                               String sFic, 
                                               int uiDureeMorc, 
                                               int uiDateSortie, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_bAjoutMorceau(Ice.AsyncResult __result);

    public boolean bSuprMorceau(String sNomMorc);

    public boolean bSuprMorceau(String sNomMorc, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, Ice.Callback __cb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, Callback_ServeurIce_bSuprMorceau __cb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, java.util.Map<String, String> __ctx, Callback_ServeurIce_bSuprMorceau __cb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bSuprMorceau(String sNomMorc, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_BoolCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_bSuprMorceau(Ice.AsyncResult __result);

    public Morceau[] getMorceaux(String sNomArt);

    public Morceau[] getMorceaux(String sNomArt, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMorceaux(String sNomArt);

    public Ice.AsyncResult begin_getMorceaux(String sNomArt, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMorceaux(String sNomArt, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMorceaux(String sNomArt, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMorceaux(String sNomArt, Callback_ServeurIce_getMorceaux __cb);

    public Ice.AsyncResult begin_getMorceaux(String sNomArt, java.util.Map<String, String> __ctx, Callback_ServeurIce_getMorceaux __cb);

    public Ice.AsyncResult begin_getMorceaux(String sNomArt, 
                                             IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getMorceaux(String sNomArt, 
                                             IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getMorceaux(String sNomArt, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getMorceaux(String sNomArt, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_GenericCallback1<Morceau[]> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Morceau[] end_getMorceaux(Ice.AsyncResult __result);
}
